---
# The purpose of this file is to define environment-specific parameters for
# ceph-osd
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tenant-ceph-osd
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: tenant-ceph-osd-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    labels:
      osd:
        node_selector_key: tenant-ceph-osd
        node_selector_value: enabled
    conf:
      storage:
        # NEWSITE-CHANGEME: The OSD count and configuration here should not need
        # to change if your HW matches the HW used in this environment.
        # Otherwise you may need to add or subtract disks to this list.
        osd:
          - data:
              type: block-logical
              location: /dev/sda
            journal:
              type: directory
              location: /var/lib/ceph/journal/journal-sda
          - data:
              type: block-logical
              location: /dev/sdb
            journal:
              type: directory
              location: /var/lib/ceph/journal/journal-sdb
          - data:
              type: block-logical
              location: /dev/sdc
            journal:
              type: directory
              location: /var/lib/ceph/journal/journal-sdc
          - data:
              type: block-logical
              location: /dev/sdd
            journal:
              type: directory
              location: /var/lib/ceph/journal/journal-sdd
          - data:
              type: block-logical
              location: /dev/sde
            journal:
              type: directory
              location: /var/lib/ceph/journal/journal-sde
          - data:
              type: block-logical
              location: /dev/sdf
            journal:
              type: directory
              location: /var/lib/ceph/journal/journal-sdf

...
